In [95]:
import numpy as np
with open("input.txt") as f:
    input_=f.read().split()
    input_= [ list(map(int, l)) for l in input_]
    
#print(np.array(input_))
rotated_array=np.rot90(input_,3)
gamma=''
epsilon=''
for sub in rotated_array:
    if(np.argmax(np.bincount(sub))):
        gamma+='1'
        epsilon+='0'
    else:
        gamma+='0'
        epsilon+='1'
print(gamma,epsilon)
print(int(gamma,2),int(epsilon,2))
print(int(gamma,2)*int(epsilon,2))
print("\n")
oxygen_array=np.copy(rotated_array)
CO2_array=np.copy(rotated_array)
def bitCriteria(rotated,args):
    #print(np.rot90(rotated,1))
    #print("\n")
    bits=''
    for i in range(len(rotated)):
        delete_indice=[]
        #print(rotated[i])
        bincount=np.bincount(rotated[i])
        if(args(bincount) or (bincount[0]==bincount[1] and args==np.argmax)  ):
            delete_indice=np.where(rotated[i] == 0)
        else:
            delete_indice=np.where(rotated[i] == 1)
        rotated=np.delete(rotated,delete_indice,1)
        #print(np.rot90(rotated,1))
        if(len(np.rot90(rotated,1))<2):
            break
        #print("\n")
    return ''.join(map(str, np.rot90(rotated,1)[0])) 
oxygen=bitCriteria(oxygen_array,np.argmax)
CO2=bitCriteria(CO2_array,np.argmin)
print("Oxygen:")
print(oxygen+",",int(oxygen,2))
print("CO2:")
print(CO2+",",int(CO2,2))
print("lifesupport:")
print(int(oxygen,2)*int(CO2,2))

010100010100 101011101011
1300 2795
3633500


Oxygen:
010100101111, 1327
CO2:
110101100101, 3429
lifesupport:
4550283


In [79]:
np.bincount([1,0])

array([1, 1], dtype=int64)

In [46]:
print(rotated_array)
np.where(rotated_array[0] != 1)


[[0 0 1 1 1 0 0 1 1 1 1 0]
 [1 0 1 0 1 0 1 0 0 0 1 0]
 [0 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 0 1 1 1 0]
 [0 0 1 0 0 1 1 1 1 0 0 0]]


(array([ 0,  1,  5,  6, 11], dtype=int64),)

In [64]:
cope=np.copy(rotated_array)
np.delete(cope,[2,3,4,7,8,9,10],1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0]])

In [97]:
import numpy as np
with open("input.txt") as f:
    input_=f.read().split()
    input_= [ list(map(int, l)) for l in input_]
    
rotated_array=np.rot90(input_,3)
gamma,epsilon='',''
for sub in rotated_array:
    if(np.argmax(np.bincount(sub))):
        gamma+='1'
        epsilon+='0'
    else:
        gamma+='0'
        epsilon+='1'
print(gamma,epsilon)
print(int(gamma,2),int(epsilon,2))
print(int(gamma,2)*int(epsilon,2))
print("\n")
oxygen_array=np.copy(rotated_array)
CO2_array=np.copy(rotated_array)
def bitCriteria(rotated,args):
    for i in range(len(rotated)):
        delete_indice=[]
        bincount=np.bincount(rotated[i])
        if(args(bincount) or (bincount[0]==bincount[1] and args==np.argmax)  ):
            delete_indice=np.where(rotated[i] == 0)
        else:
            delete_indice=np.where(rotated[i] == 1)
        rotated=np.delete(rotated,delete_indice,1)
        if(len(np.rot90(rotated,1))<2):
            break
    return ''.join(map(str, np.rot90(rotated,1)[0])) 
oxygen=bitCriteria(oxygen_array,np.argmax)
CO2=bitCriteria(CO2_array,np.argmin)
print("Oxygen:")
print(oxygen+",",int(oxygen,2))
print("CO2:")
print(CO2+",",int(CO2,2))
print("lifesupport:")
print(int(oxygen,2)*int(CO2,2))

010100010100 101011101011
1300 2795
3633500


Oxygen:
010100101111, 1327
CO2:
110101100101, 3429
lifesupport:
4550283
